// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gazgmgqnfefodcrkmcnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhemdtZ3FuZmVmb2RjcmttY25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTU4ODMsImV4cCI6MjA2NTQ3MTg4M30.wKy4FNL36MEAGl4MktBE5pd8800zl274T5jb3MDuBgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);